### PR TITLE
ci: created github-issue-sync workflow file

### PR DESCRIPTION
**Pull request by Bullrich**
Created the GitHub Issue Sync action workflow file.

This PR is related to https://github.com/paritytech/github-issue-sync/issues/57

### CODE REVIEW

**Review by vas3k — APPROVED** [review]

**Review by mordamax — CHANGES_REQUESTED** [review]
This project shouldn't go to our board anymore. But if @vas3k has their own board, we can just change a project ID and some other fields

**Comment by Bullrich** [comment]
> This project shouldn't go to our board anymore. But if @vas3k has their own board, we can just change a project ID and some other fields

@vas3k please advice on what I should do.

**Comment by vas3k** [comment]
@Bullrich you opened this PR so what are you trying to achieve? :)

We don't have any project boards in our team, we manage our projects differently

**Comment by Bullrich** [comment]
> @Bullrich you opened this PR so what are you trying to achieve? :)
> 
> We don't have any project boards in our team, we manage our projects differently

If you don't have any I will close the PR. The reason for which I opened it was because there was a config aiming to this repo in the server version of this bot, but seeing that it is not necessary anymore I shall simply ignore it.

**Pull request closed without merging**
